In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("train.csv")
df.shape

(404290, 6)

In [5]:
newdf = df.copy()
newdf

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1
404287,404287,537928,537929,What is one coin?,What's this coin?,0
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [6]:
newdf.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [16]:
newdf = df.sample(30000)

In [17]:
newdf

,id,qid1,qid2,question1,question2,is_duplicate
383184,383184,515116,515117,Has Donald Trump killed the Republican Party?,Is it possible that Donald Trump could split t...,0
72361,72361,124347,124348,"What is a ""cousin-brother"" or ""cousin-sister""?","Is it correct to use ""cousin brother"" or ""cous...",0
63804,63804,110972,110973,I am looking for a change of career into IT . ...,I am a 35-year-old Java developer and I don't ...,0
352620,352620,481546,481547,What if I masturbate daily?,If I did masturbate daily?,1
20748,20748,39123,39124,What kind of placements are available for Chem...,Is Singapore a good place for chemical engineers?,0
...,...,...,...,...,...,...
73780,73780,126556,52245,How many days does it take to have periods aft...,Can I take two birth control pills the first d...,0
114849,114849,187386,187387,How to get rid of small cockroaches in a house?,How do I get rid of little cockroaches in my h...,1
198289,198289,299461,299462,Can protons collide each other?,Why don't neutrons and protons collide with ea...,0
272521,272521,106028,188208,What do the different colors of lights in an E...,What is the difference between primary colors ...,0
219920,219920,326917,59286,Who is the biggest traitor in the history of t...,Who is the biggest traitor in U.S. history?,1

In [27]:
newdf.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [28]:
newdf.duplicated().sum()

np.int64(0)

In [29]:
ques_df = newdf[['question1','question2']]
ques_df.head()

,question1,question2
383184,Has Donald Trump killed the Republican Party?,Is it possible that Donald Trump could split t...
72361,"What is a ""cousin-brother"" or ""cousin-sister""?","Is it correct to use ""cousin brother"" or ""cous..."
63804,I am looking for a change of career into IT . ...,I am a 35-year-old Java developer and I don't ...
352620,What if I masturbate daily?,If I did masturbate daily?
20748,What kind of placements are available for Chem...,Is Singapore a good place for chemical engineers?

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
questions = list(ques_df['question1']) + list(ques_df['question2'])
cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [31]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [32]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
383184,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72361,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
352620,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73780,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114849,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198289,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
272521,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
219920,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
temp_df['is_duplicate'] = newdf['is_duplicate']

In [34]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
383184,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72361,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
352620,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73780,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114849,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198289,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
272521,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
219920,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=42)

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7365