In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"C:\Users\anjal\OneDrive\Quora_question_pair\Data\train.csv")
df.shape

(404290, 6)

In [3]:
newdf = df.copy()
newdf

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1
404287,404287,537928,537929,What is one coin?,What's this coin?,0
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [4]:
newdf.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [5]:
newdf = df.sample(30000)

In [6]:
newdf

,id,qid1,qid2,question1,question2,is_duplicate
202903,202903,83227,305346,How do I get more than 1K upvotes for our answ...,How can I get more upvotes on my Quora answers?,1
12294,12294,23698,23699,What are some of the best frozen garlic bread ...,Do we have any Rasta Rap Singers?,0
59468,59468,104148,104149,Want to know which will be best food packaging...,Which are the best food packaging exhibition i...,1
177657,177657,1961,5746,Is it physically possible to travel back in time?,Will time travel be possible in future?,1
331283,331283,146527,52207,How do Yahoo Answer questions differ from Quor...,"What are the differences between Quora, Reddit...",0
...,...,...,...,...,...,...
311385,311385,6672,52675,Who will be a better president Donald Trump or...,Who is better among Hillary Clinton and Donald...,1
392573,392573,120009,194206,Is IELTS or pte easier?,Which is easier: PTE or IELTS?,1
144197,144197,228279,31199,"India being top most economy in the world, can...",How can GST be beneficial to the Indian economy?,0
245125,245125,357895,357896,Do all Converse employees wear sneakers to work?,Is it ok to wear sneakers to a casual first date?,0
243205,243205,355601,355602,"What is the location of Palawan, and how does ...","What is the location of Palawan, and how does ...",0

In [7]:
newdf.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [8]:
newdf.duplicated().sum()

np.int64(0)

In [9]:
ques_df = newdf[['question1','question2']]
ques_df.head()

,question1,question2
202903,How do I get more than 1K upvotes for our answ...,How can I get more upvotes on my Quora answers?
12294,What are some of the best frozen garlic bread ...,Do we have any Rasta Rap Singers?
59468,Want to know which will be best food packaging...,Which are the best food packaging exhibition i...
177657,Is it physically possible to travel back in time?,Will time travel be possible in future?
331283,How do Yahoo Answer questions differ from Quor...,"What are the differences between Quora, Reddit..."

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
questions = list(ques_df['question1']) + list(ques_df['question2'])
cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [11]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [12]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
202903,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12294,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59468,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
177657,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
331283,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392573,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
144197,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
245125,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
243205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
temp_df['is_duplicate'] = newdf['is_duplicate']

In [14]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
202903,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12294,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59468,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
177657,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
331283,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
392573,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
144197,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
245125,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
243205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=42)

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.751